version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local