CREATE TABLE expense
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    amount      DOUBLE PRECISION,
    description VARCHAR(255),
    category    VARCHAR(255),
    date        VARCHAR(255),
    category_id BIGINT,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);