CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE expense
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    amount      DOUBLE PRECISION,
    description VARCHAR(255),
    date        VARCHAR(255),
    category_id BIGINT,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);