CREATE TABLE budget
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date date,
    end_date   date,
    CONSTRAINT pk_budget PRIMARY KEY (id)
);

CREATE TABLE budget_category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    "limit"   DECIMAL,
    budget_id BIGINT,
    CONSTRAINT pk_budgetcategory PRIMARY KEY (id)
);

ALTER TABLE budget_category
    ADD CONSTRAINT FK_BUDGETCATEGORY_ON_BUDGET FOREIGN KEY (budget_id) REFERENCES budget (id);